### ISSUE TITLE
Errors on Ubuntu

### ISSUE THREAD

**Issue by vitr** [born2net/ng2Boilerplate#12]
Here is my ec2 instance
```
uname -a
Linux ip-172-31-53-90 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

node -v
v5.7.0

npm -v
3.6.0

gulp -v
[12:05:08] CLI version 3.9.1
[12:05:08] Local version 3.9.1

```
and my attempt to run (used sudo just in case...)

```
:~/ng2Boilerplate$ sudo gulp production
[11:57:31] Using gulpfile ~/ng2Boilerplate/gulpfile.js
[11:57:31] Starting 'production'...
[11:57:31] Starting 'x_clean'...
[11:57:31] Finished 'x_clean' after 171 ms
[11:57:31] Starting 'x_assets'...
[11:57:31] Finished 'x_assets' after 21 ms
[11:57:31] Starting 'x_copy_files'...
[11:57:36] Finished 'x_copy_files' after 5.02 s
[11:57:36] Starting 'x_build-ts'...
/home/ubuntu/ng2Boilerplate/node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
src/App.ts(6,28): error TS2307: Cannot find module 'immutable'.
src/comps/app1/todos/reducers/TodoReducer.ts(1,20): error TS2307: Cannot find module 'immutable'.
src/models/StoreModel.ts(1,19): error TS2307: Cannot find module 'immutable'.
src/reducers/AppdbReducer.ts(1,19): error TS2307: Cannot find module 'immutable'.
src/reducers/NotifyReducer.ts(1,19): error TS2307: Cannot find module 'immutable'.
src/services/AuthService.ts(4,14): error TS2503: Cannot find namespace 'Immutable'.
/home/ubuntu/ng2Boilerplate/typings/app.d.ts(26,1): error TS6053: File '/home/ubuntu/ng2Boilerplate/node_modules/immutable/dist/Immutable.d.ts' not found.
[11:57:45] TypeScript: 8 semantic errors
[11:57:45] TypeScript: emit succeeded (with errors)
[11:57:45] Finished 'x_build-ts' after 8.47 s
[11:57:45] Starting 'x_copy'...
[11:57:45] Finished 'x_copy' after 988 μs
[11:57:45] Starting 'x_bundle'...
     Building the single-file sfx bundle for src/App.js...

err  Error: ENOENT: no such file or directory, open '/home/ubuntu/ng2Boilerplate/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.js'
         at Error (native)
        Error loading file:///home/ubuntu/ng2Boilerplate/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.js
[11:57:46] 'x_bundle' errored after 923 ms
[11:57:46] Error: Command jspm bundle-sfx src/App.js ./dist/index.js --skip-source-maps failed with exit code 1
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
An error occured in task 'x_bundle'.
[11:57:46] 'production' errored after 15 s
[11:57:46] Error in plugin 'run-sequence'
Message:
    An error occured in task 'x_bundle'.

```

**Comment by born2net** [comment]
update to 0.14
