### ISSUE TITLE
npm install && gulp development...

### ISSUE THREAD

**Issue by ceballos59** [born2net/ng2Boilerplate#16]
D:\meanproject\ng2Boilerplate>node --version
v5.10.1

D:\meanproject\ng2Boilerplate>npm --version
3.8.3

D:\meanproject\ng2Boilerplate>
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
logger.js:20 TypeScript transpiling to CommonJS, consider setting module: "system" in typescriptOptions to transpile directly to System.register format
browser_adapter.ts:88EXCEPTION: RangeError: Maximum call stack size exceeded
browser_adapter.ts:78EXCEPTION: RangeError: Maximum call stack size exceededBrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:78
browser_adapter.ts:78RangeError: Maximum call stack size exceeded
    at e.scheduleTask (zone.min.js:1)
    at e.scheduleMicroTask (zone.min.js:1)
    at h (zone.min.js:1)
    at e.then [as __zone_symbol__then] (zone.min.js:1)
    at n (zone.min.js:1)
    at r (zone.min.js:1)
    at e.scheduleTask (zone.min.js:1)
    at e.scheduleMicroTask (zone.min.js:1)
    at h (zone.min.js:1)
    at e.then [as __zone_symbol__then] (zone.min.js:1)BrowserDomAdapter.logError @ browser_adapter.ts:78
index.html:31 Error: EXCEPTION: Error during instantiation of ApplicationRef_! (ApplicationRef -> ApplicationRef_).(…) "error system.js Error: EXCEPTION: Error during instantiation of ApplicationRef_! (ApplicationRef -> ApplicationRef_).
	ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
	ORIGINAL STACKTRACE:
	RangeError: Maximum call stack size exceeded
	    at e.scheduleTask (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:7777)
	    at e.scheduleMicroTask (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:5493)
	    at h (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:3406)
	    at e.then [as __zone_symbol__then] (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:10040)
	    at n (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:2197)
	    at r (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:2226)
	    at e.scheduleTask (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:7736)
	    at e.scheduleMicroTask (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:5493)
	    at h (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:3406)
	    at e.then [as __zone_symbol__then] (http://localhost:8080/jspm_packages/npm/zone.js@0.6.12/dist/zone.min.js:1:10040)
	Evaluating http://localhost:8080/src/App.ts
	Error loading http://localhost:8080/src/App.ts"

**Comment by born2net** [comment]
upd to latest ver
