### ISSUE TITLE
gulp production result in error while x_bundle

### ISSUE THREAD

**Issue by JanOschii** [born2net/ng2Boilerplate#23]
Hi,

for your information. I get following error if i try to use ```gulp production``` on an fresh installed project:
```
     Building the bundle tree for src/App.js...

err  Error on fetch for ng2Boilerplater/App.js.ts at file:///C:/Users/Admin/.angular2/front/src/App.js.ts
  Error: ENOENT: no such file or directory, open 'C:\Users\Admin\.angular2\front\src\App.js.ts'
    at Error (native)
```
This App**.js.ts** is somehow strange.
It seems like it is a bug comming with jspm 0.17+. I tried the other gulp **x_bundle** task by commenting out the new one for 0.17+ and activating the old one for jspm 0.16 in the gulpfile.js
It is passing the x_bundle task somehow. I commented out the "rsync" task. It now finished the production sequence. But, in the result I get this errors.

```
[04:39:38] Starting 'production'...
[04:39:38] Starting 'x_clean'...
[04:39:39] Finished 'x_clean' after 446 ms
[04:39:39] Starting 'x_assets'...
[04:39:39] Finished 'x_assets' after 79 ms
[04:39:39] Starting 'x_copy_files'...
[04:39:52] Finished 'x_copy_files' after 13 s
[04:39:52] Starting 'x_build-ts'...
[04:40:01] Finished 'x_build-ts' after 8.78 s
[04:40:01] Starting 'x_copy'...
[04:40:01] Finished 'x_copy' after 1.6 ms
[04:40:01] Starting 'x_bundle'...

err  bundle-sfx has been renamed to build.
  Use jspm build src/App.js ./dist/index.js --skip-source-maps
[04:40:02] Finished 'x_bundle' after 1.26 s
[04:40:02] Starting 'x_minify'...
[04:40:02] Finished 'x_minify' after 2.03 ms
[04:40:02] Starting 'x_target'...
[04:40:02] Finished 'x_target' after 3.59 ms
[04:40:02] Starting 'x_open_server_bundle'...
[04:40:02] Finished 'x_open_server_bundle' after 61 ms
FINISHED SUCCESSFULLY
[04:40:02] Finished 'production' after 24 s
C:\Users\Admin\.angular2\front\node_modules\rx\dist\rx.all.js:9772
      throw new Error('Invalid arguments');
      ^
      ^

Error: Invalid arguments
    at Subject.observableProto.delay (C:\Users\Admin\.angular2\front\node_modules\rx\dist\rx.all.js:9772:13)
    at C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\file-watcher.js:128:41
    at Array.reduce (native)
    at getObservable (C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\file-watcher.js:125:24)
    at module.exports.plugin (C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\file-watcher.js:16:19)
    at Object.module.exports.setFileWatchers [as fn] (C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\async.js:170:63)
    at C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\browser-sync.js:149:14
    at iterate (C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\utils.js:268:13)
    at C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\utils.js:277:25
    at executeTask (C:\Users\Admin\.angular2\front\node_modules\browser-sync\lib\browser-sync.js:170:13)
```
Is there a good workaround to get out a production build.
 Thanks,

Jan

**Comment by born2net** [comment]
could not reproduce
