### ISSUE TITLE
Installation broken: Cannot find module 'gulp-tslint-stylish'

### ISSUE THREAD

**Issue by ihorskyi** [born2net/ng2Boilerplate#7]
npm i
...
```
ok   Loader files downloaded successfully

ok   Install complete.
module.js:339
    throw err;
    ^

Error: Cannot find module 'gulp-tslint-stylish'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ihorskyi/dev/playground/ng2Boilerplate/gulpfile.js:20:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by born2net** [comment]
tx fixing asap
